// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://diqhtfvrlodatadurzpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpcWh0ZnZybG9kYXRhZHVyenBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjUwMjIsImV4cCI6MjA2Mzg0MTAyMn0.U4zxmxl6Q_A4ye724J9YqgCYzGLKWAfB4rapFK1iQqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);